[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
clockwork_counter = "Fit6msXwWsyuNncCpPt93snET1eEGh1AY9ZcZvAyi2Jk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/spidey/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
